Repository gideonmaina/gideonmaina.github.io, pull requests merged in 2025-07, with the labels that each got.

#6 Update/contact
  src/pages/api/contact.js
  src/pages/contact.astro
Labels: enhancement, Security

#10 Update contact page
  src/layouts/AppFooter.astro
  src/pages/api/contact.js
  src/pages/contact.astro
Labels: bug, enhancement

#11 Update home page content
  src/pages/api/contact.js
  src/pages/index.astro
Labels: enhancement

#12 fix: remove functions config to resolve Vercel serverless function pattern error
  vercel.json
Labels: bug
